print("Hola mundo de nuevo!!!")
print("Coloca tu nombre: ")
x = input()
print("Hola ", x)
print("PALABRA CLAVE END----------")
print("Hola",end=" ")
print(x)
print("Python", end=". ")
print("Es genial!")

print("LAB CISCO - 2.1.1.20, REDUCE THE FOLLOWING CODE-------");

print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
#REDUCING CODE:
print("Reducing code: ")
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")
print("More bigger arrow: ")
print("    *")
print("    *")
print("   * *")
print("   * *")
print("  *   *")
print("  *   *")
print(" *     *")
print(" *     *")
print("***   ***")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *   *")
print("  *****")
#arrow twice
print("    *    "*2)
print("   * *   "*2)
print("  *   *  "*2)
print(" *     * "*2)
print("***   ***"*2)
print("  *   *  "*2)
print("  *   *  "*2)
print("  *****  "*2)


